nav:
  - 'About Uxios':
    - 'features.md'
    - 'why-use-uxios-instead-of-unitywebrequest.md'
    - 'why-axios.md'
    - 'contributing.md'
    - 'changelog.md'
  - 'Documentation':
    - 'getting-started.md'
    - 'Guides':
        - 'guides/fetching-pokemon.md' 
        - 'guides/fetching-pokemon-using-get.md' 
        - 'guides/fetching-untyped-json-responses.md' 
        - 'guides/logging-to-the-console.md' 
        - 'guides/building-an-automatic-loader.md' 
    - 'Explanation':
        - 'explanation/promises.md'
        - 'explanation/interceptors.md'
    - 'Reference':
        - 'reference/request.md'
        - 'reference/response.md'

# Includes, starting with an underscore - https://www.mkdocs.org/user-guide/configuration/#not_in_nav
not_in_nav: |
  _*.md
  index.md

site_name: ""
docs_dir: "Documentation~"
site_description: "A Unity-native, Axios-inspired HTTP client for streamlined, typed, and extensible networking across platforms."
extra_css:
  - "css/utilities.css"
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.ico
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    - navigation.path
    - navigation.footer
    - navigation.tracking
    - content.tabs.link

plugins:
  - search:

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
